"""
governance/nrmo_core.py — NRMO Core: VETO ONLY
================================================
LAYER: GOVERNANCE

Contract:
  Input:  state X_t, world ω, thresholds
  Output: admissible action set A_t, veto flags

NRMO Core issues: YES / NO / HOLD.
NRMO Core does NOT: rank, score, optimise, select, advise.

The Engine receives A_t and searches within it.
The Engine CANNOT modify, override, or reinterpret A_t.

Formal: A_t = NRMO(X_t)
        a_t = Engine(A_t)
"""
from __future__ import annotations
import numpy as np
from typing import List, Tuple
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from core.state import CivState
from config.defaults import NRMOCoreConfig, TuningConfig

# ═══════════════════════════════════════════════
# Veto functions — return True = REJECT
# ═══════════════════════════════════════════════

def nrmo_veto(a: np.ndarray, s: CivState, c: NRMOCoreConfig) -> bool:
    """Original NRMO veto. SOURCE: monograph baseline."""
    g, sf, lr, di = a
    if g > c.growth_hard_cap: return True
    if s.X > c.high_exposure_threshold and g > c.high_exposure_growth_cap: return True
    if s.E < c.low_env_threshold and g > c.low_env_growth_cap: return True
    if s.G < c.low_gov_threshold and di < c.low_gov_dist_floor: return True
    return False

def nrmo_vnext_veto(a: np.ndarray, s: CivState,
                    nc: NRMOCoreConfig, tc: TuningConfig) -> bool:
    """vNext veto = original + exploration floor + eco cap + governance repair.
    SOURCE: monograph vNext."""
    g, sf, lr, di = a
    if g > tc.growth_cap: return True
    if s.X > tc.high_stakes_trigger_exposure and g > nc.high_exposure_growth_cap: return True
    if s.E < tc.high_stakes_trigger_environment and g > nc.low_env_growth_cap: return True
    if s.E < 45 and g > tc.eco_growth_cap: return True
    if s.G < tc.high_stakes_trigger_governance and di < tc.governance_repair_floor: return True
    if lr < tc.exploration_floor: return True
    if s.G < 30 and di < 0.20: return True
    return False

# ═══════════════════════════════════════════════
# Admissible set construction
# ═══════════════════════════════════════════════

def construct_admissible_set(
    candidates: List[np.ndarray],
    s: CivState,
    mode: str,
    nc: NRMOCoreConfig = NRMOCoreConfig(),
    tc: TuningConfig = None,
) -> Tuple[List[np.ndarray], List[bool]]:
    """
    GOVERNANCE FUNCTION: Construct admissible set from candidate pool.

    Input:  raw candidates (generated by engine, unknown to governance)
    Output: (admissible_list, veto_flags)

    mode: 'nrmo' | 'vnext' | 'none'

    This is the BOUNDARY. Engine receives admissible_list only.
    Engine never sees the veto logic or thresholds.
    """
    if mode == "none":
        return list(candidates), [False] * len(candidates)

    tc = tc or TuningConfig()
    admissible = []
    flags = []
    for c in candidates:
        if mode == "nrmo":
            vetoed = nrmo_veto(c, s, nc)
        elif mode == "vnext":
            vetoed = nrmo_vnext_veto(c, s, nc, tc)
        else:
            vetoed = False
        flags.append(vetoed)
        if not vetoed:
            admissible.append(c)
    return admissible, flags
