"""
governance/nrmo_core.py — NRMO Core: VETO ONLY
================================================
LAYER: GOVERNANCE

Contract:
  Input:  state X_t, world ω, thresholds
  Output: admissible action set A_t, veto flags

NRMO Core issues: YES / NO / HOLD.
NRMO Core does NOT: rank, score, optimise, select, advise.

The Engine receives A_t and searches within it.
The Engine CANNOT modify, override, or reinterpret A_t.

Formal: A_t = NRMO(X_t)
        a_t = Engine(A_t)
"""
from __future__ import annotations
import numpy as np
from typing import List, Tuple
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from core.state import CivState
from config.defaults import NRMOCoreConfig, TuningConfig

# ═══════════════════════════════════════════════
# Veto functions — return True = REJECT
# ═══════════════════════════════════════════════

def nrmo_veto(a: np.ndarray, s: CivState, c: NRMOCoreConfig) -> bool:
    """Original NRMO veto. SOURCE: monograph baseline."""
    g, sf, lr, di = a
    if g > c.growth_hard_cap: return True
    if s.X > c.high_exposure_threshold and g > c.high_exposure_growth_cap: return True
    if s.E < c.low_env_threshold and g > c.low_env_growth_cap: return True
    if s.G < c.low_gov_threshold and di < c.low_gov_dist_floor: return True
    return False

def nrmo_vnext_veto(a: np.ndarray, s: CivState,
                    nc: NRMOCoreConfig, tc: TuningConfig) -> bool:
    """vNext veto = original + exploration floor + eco cap + governance repair.
    SOURCE: monograph vNext."""
    g, sf, lr, di = a
    if g > tc.growth_cap: return True
    if s.X > tc.high_stakes_trigger_exposure and g > nc.high_exposure_growth_cap: return True
    if s.E < tc.high_stakes_trigger_environment and g > nc.low_env_growth_cap: return True
    if s.E < 45 and g > tc.eco_growth_cap: return True
    if s.G < tc.high_stakes_trigger_governance and di < tc.governance_repair_floor: return True
    if lr < tc.exploration_floor: return True
    if s.G < 30 and di < 0.20: return True
    return False

# ═══════════════════════════════════════════════
# Admissible set construction
# ═══════════════════════════════════════════════

def construct_admissible_set(
    candidates: List[np.ndarray],
    s: CivState,
    mode: str,
    nc: NRMOCoreConfig = NRMOCoreConfig(),
    tc: TuningConfig = None,
) -> Tuple[List[np.ndarray], List[bool]]:
    """
    GOVERNANCE FUNCTION: Construct admissible set from candidate pool.

    Input:  raw candidates (generated by engine, unknown to governance)
    Output: (admissible_list, veto_flags)

    mode: 'nrmo' | 'vnext' | 'none'

    This is the BOUNDARY. Engine receives admissible_list only.
    Engine never sees the veto logic or thresholds.
    """
    if mode == "none":
        return list(candidates), [False] * len(candidates)

    tc = tc or TuningConfig()
    admissible = []
    flags = []
    for c in candidates:
        if mode == "nrmo":
            vetoed = nrmo_veto(c, s, nc)
        elif mode == "vnext":
            vetoed = nrmo_vnext_veto(c, s, nc, tc)
        else:
            vetoed = False
        flags.append(vetoed)
        if not vetoed:
            admissible.append(c)
    return admissible, flags

# ═══════════════════════════════════════════════
# v7.2 ADDITION — Horizon-Integrated veto
# SOURCE: ch27_time_horizon.tex (v7.2), docs/proposal_ch27_time_horizon_v2.md
# STATUS: PROPOSAL-GRADE, UNVALIDATED. Additive only — does not modify
#         nrmo_veto() / nrmo_vnext_veto() / construct_admissible_set()
#         above. Existing modes ('nrmo', 'vnext', 'none') are unchanged.
# ═══════════════════════════════════════════════
from core.viability import passive_ruin_window_signal

DEFAULT_HORIZON_SET = [1, 12, 60, 240, 600]  # Immediate/OneYear/FiveYear/TwentyYear/FiftyYear
# analogues (see ch27 v7.2 Table: cognitive horizon <-> simulation step mapping,
# extended with an Immediate=1-step entry). Calibration TBD — see open items.


def nrmo_v72_veto(
    candidate_action,
    s: "CivState",
    wp: dict,
    rng,
    cfg,
    nc: "NRMOCoreConfig",
    tc: "TuningConfig" = None,
    horizon_set=None,
    viability_threshold: float = 0.5,
    n_rollouts: int = 30,
) -> dict:
    """
    v7.2 veto: True Ruin (absolute, unconditional) + Passive Ruin
    (choice-time window-closure detection), combined per ch27 v7.2 §4.

    Returns a dict (not a bare bool) so the caller retains the
    diagnostic breakdown — this mirrors ch27's NRMO_CORE.veto()
    pseudocode, adapted to this codebase's existing function-based
    (not class-based) governance style.

    Cheap check first: reuse the existing instant threshold veto
    (nrmo_vnext_veto) before running the (expensive) rollout-based
    Passive Ruin check. If the cheap check already rejects, skip
    the rollout entirely.
    """
    tc = tc or TuningConfig()
    horizon_set = horizon_set or DEFAULT_HORIZON_SET

    if nrmo_vnext_veto(candidate_action, s, nc, tc):
        return {"verdict": "REJECT_TRUE_RUIN_INSTANT", "binding_horizon": None}

    signal, binding_h = passive_ruin_window_signal(
        s, candidate_action, wp, rng, cfg, horizon_set,
        threshold=viability_threshold, n_rollouts=n_rollouts,
    )
    if signal:
        return {"verdict": "REJECT_PASSIVE_RUIN", "binding_horizon": binding_h}

    return {"verdict": "ALLOW", "binding_horizon": None}


def construct_admissible_set_v72(
    candidates,
    s: "CivState",
    wp: dict,
    rng,
    cfg,
    nc: "NRMOCoreConfig" = None,
    tc: "TuningConfig" = None,
    horizon_set=None,
    viability_threshold: float = 0.5,
    n_rollouts: int = 30,
):
    """
    v7.2 variant of construct_admissible_set(). Additive — the
    original function above is untouched and remains the default
    ('nrmo' / 'vnext' / 'none' modes). Callers opt into this
    explicitly; it is not wired into any existing pipeline call site
    by this commit.
    """
    nc = nc or NRMOCoreConfig()
    tc = tc or TuningConfig()
    admissible, verdicts = [], []
    for c in candidates:
        v = nrmo_v72_veto(c, s, wp, rng, cfg, nc, tc,
                          horizon_set, viability_threshold, n_rollouts)
        verdicts.append(v)
        if v["verdict"] == "ALLOW":
            admissible.append(c)
    return admissible, verdicts

# ═══════════════════════════════════════════════
# v7.2.1 ADDITION — Delta-based Passive Ruin veto
# SOURCE: empirical finding, 2026-08-27 diagnostic session.
# Absolute-threshold detection (nrmo_v72_veto, passive_ruin_window_signal)
# was found to lose sensitivity at long horizons (mean-reversion in
# transition() washes out the single-action signal against a fixed
# 0.5 cutoff: observed firing rate 0/12, 0/12, 3/12, 0/12 across
# 1/5/10/20-year horizons on a 12-candidate diagnostic sweep).
# Delta-based detection (candidate-vs-do-nothing, same horizon)
# improved this to 1/12, 1/12, 4/12, 2/12 on the same sweep — the
# 20-year collapse to zero is resolved, though sensitivity is not
# perfectly monotonic (small, noisy sample; see docs/ for the raw run).
# Both veto variants are retained (additive) for comparison.
# ═══════════════════════════════════════════════
from core.viability import passive_ruin_delta_signal


def nrmo_v72_1_veto(
    candidate_action, s, wp, rng, cfg, nc, tc=None,
    horizon_set=None, degradation_threshold: float = 0.15,
    n_rollouts: int = 30,
) -> dict:
    """v7.2.1: same structure as nrmo_v72_veto, but uses the
    delta-based (candidate-vs-do-nothing) Passive Ruin signal instead
    of the absolute-threshold one. Preferred variant pending further
    validation; nrmo_v72_veto retained for A/B comparison."""
    tc = tc or TuningConfig()
    horizon_set = horizon_set or DEFAULT_HORIZON_SET

    if nrmo_vnext_veto(candidate_action, s, nc, tc):
        return {"verdict": "REJECT_TRUE_RUIN_INSTANT", "binding_horizon": None, "delta": None}

    signal, binding_h, delta = passive_ruin_delta_signal(
        s, candidate_action, wp, rng, cfg, horizon_set,
        degradation_threshold=degradation_threshold, n_rollouts=n_rollouts,
    )
    if signal:
        return {"verdict": "REJECT_PASSIVE_RUIN", "binding_horizon": binding_h, "delta": delta}

    return {"verdict": "ALLOW", "binding_horizon": None, "delta": None}
